version: "3.5"
services:
  php_fpm:
    build: ./php
    container_name: cake_nuxt_php
    working_dir: /var/www/app
    networks:
      - app
    volumes:
      - ./php/app:/var/www/app:cached

  nginx:
    image: nginx:1.15
    container_name: cake_nuxt_nginx
    networks:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
      - node

  mysql:
    image: mysql:5.7
    container_name: cake_nuxt_mysql
    command: --sql_mode=""
    volumes:
      - ./mysql/files/:/var/lib/mysql
    networks:
      - app
    environment:
      - MYSQL_DATABASE=cake_nuxt
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345

  node:
    build: ./nodejs
    container_name: cake_nuxt_node
    volumes:
      - ./nodejs/app:/var/www/app
      - /var/www/app/node_modules
    networks:
      - app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - php_fpm

networks:
  app:
    driver: bridge
